title: '5565'
description: nb
steps:
  - course: githubtraining/introduction-to-github
    description: fty
    title: pin
    link: go
    video: 'https://guides.github.com/activities/hello-world/'
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
    description: '66767'
    link: 2go
    video: 'https://help.github.com/articles/viewing-contributions'
